### ISSUE TITLE
WOTLK Classic: Activations not persisting on action bar button updates

### ISSUE THREAD

**Issue by oscarburga** [rgd87/ClassicSpellActivations#17]
Spell activations on action bar buttons are not updating properly through action bar button updates (i.e.: macros that use #showtooltip and perform different actions based on alt/shift/ctrl modifiers, presumably happens on action bar paging aswell). 

Macro I used to test (warlock with backlash talent):
```
#showtooltip
/cast [nomod] Incinerate
/cast [mod:shift] Summon Voidwalker
/cast [mod:alt, @focus] Incinerate
/cast [mod:ctrl] Shadow Bolt
```
Steps to reproduce (happens with both Dominos action bars and default blizzard action bars): 

1. Get a backlash proc. Notice spell activation works perfectly at first, incinerate lights up properly. 
2. Hold down shift, ctrl or alt to trigger the ability and tooltip change on the macro button. Activation disappears. 
2.1. _**Bug 1:** Activation disappears even if using a modifier for the same or other spells that are also affected by the proc (i.e.: activation disappears even if using "alt" for Incinerate cast on focus, or "ctrl" for Shadow Bolt even though Shadow Bolt is also affected by Backlash)._
3. Stop pressing the modifier key pressed down. Spell activation does not get restored when the button updates.

Quick gif illustrating the issue:
![spellactivations](https://user-images.githubusercontent.com/51001981/198899914-9e425b7b-ab0e-4b6d-80d5-c99fd65aa77a.gif)

**Comment by d87** [comment]
Should work in the latest update (3.0.9)
