### ISSUE TITLE
[Wrath Classic][Dominos10] Activation overlay not showing - no Lua errors

### ISSUE THREAD

**Issue by Road-block** [rgd87/ClassicSpellActivations#20]
It doesn't seem to work for Wrath Classic (3.4.1) with Dominos v10.x
Tests done:
- Paladin, Hammer of Wrath button (usable on enemies < 20% hp)
- Dragged the ability to a Dominos bar that re-uses Blizzard ActionButton[N] -> no spell effect
- Dragged the ability to a Dominos bar that creates its own DominosActionButton[N] -> no spell effect

Addon versions at time of test.
ClassicSpellActivations: 3.0.15
Dominos: 10.1.1-beta1-wrath
WoW Client: 3.4.1.49345 enUS

**Comment by d87** [comment]
I had nothing to do with Dominos, HoW was broken and no one said anything
